// <auto-generated />
using System;
using Financial;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Financial.Migrations
{
    [DbContext(typeof(DBinterface))]
    [Migration("20181120174250_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Financial.Account", b =>
                {
                    b.Property<int>("AccountNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("EmailAddress")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName");

                    b.Property<decimal>("Income");

                    b.Property<decimal>("Interest");

                    b.Property<string>("LastName");

                    b.Property<decimal>("PercentOfSalarySaved");

                    b.Property<int>("YearsInPeriod");

                    b.HasKey("AccountNumber")
                        .HasName("PK_Account");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("Financial.InvestmentTracker", b =>
                {
                    b.Property<int>("TrackerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccountNumber");

                    b.Property<decimal>("Income");

                    b.Property<decimal>("Interest");

                    b.Property<decimal>("PercentOfSalarySaved");

                    b.Property<int>("YearsInPeriod");

                    b.HasKey("TrackerID")
                        .HasName("PK_Transaction");

                    b.HasIndex("AccountNumber");

                    b.ToTable("InvestmentTracker");
                });

            modelBuilder.Entity("Financial.InvestmentTracker", b =>
                {
                    b.HasOne("Financial.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountNumber")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
